"use client";

import { useEffect } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { useBanks } from "@/context/BankContext";
import { useAuth } from "@/context/AuthContext";
import { useToast } from "@/context/ToastContext";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { formatCurrency } from "@/lib/utils";
import { ChevronLeft, Calculator, Download, CreditCard, AlertTriangle, CheckCircle2, TrendingUp } from "lucide-react";

export default function TaxPage() {
  const { banks, totalBalance, TAX_RATE } = useBanks();
  const { isAuthenticated, ready } = useAuth();
  const { showToast } = useToast();
  const router = useRouter();

  useEffect(() => {
    if (!ready) return;
    if (!isAuthenticated) {
      showToast("Login required!", "warning");
      router.replace("/login?reason=protected");
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [ready, isAuthenticated]);

  const totalTax = totalBalance * TAX_RATE;

  function handlePayTax() {
    alert(`Tax payment of ${formatCurrency(totalTax)} initiated.\n\nDemo only — no actual payment processed.`);
  }

  function handleDownload() {
    const lines = [
      "BANKFLOW — TAX SUMMARY REPORT",
      "================================",
      `Report Date : ${new Date().toLocaleDateString("en-BD")}`,
      `Tax Rate    : ${(TAX_RATE*100).toFixed(0)}% per bank`,
      "",
      "BANK-WISE BREAKDOWN",
      "-------------------",
      ...banks.map((b,i)=>`${i+1}. ${b.bankName.padEnd(32)} Balance: ৳${b.balance.toLocaleString().padStart(12)} | Tax: ৳${(b.balance*TAX_RATE).toLocaleString().padStart(10)}`),
      "","-------------------",
      `TOTAL BALANCE : ৳${totalBalance.toLocaleString()}`,
      `TOTAL TAX     : ৳${totalTax.toLocaleString()}`,
      "","Generated by BankFlow — Demo purposes only",
    ];
    const blob = new Blob([lines.join("\n")],{type:"text/plain"});
    const url  = URL.createObjectURL(blob);
    const a    = document.createElement("a");
    a.href=url; a.download="bankflow-tax-report.txt"; a.click();
    URL.revokeObjectURL(url);
  }

  if (!ready || !isAuthenticated) {
    return (
      <div className="flex flex-col min-h-screen">
        <Navbar />
        <main className="flex-1 flex items-center justify-center">
          <div className="w-8 h-8 border-4 border-indigo-200 border-t-indigo-500 rounded-full animate-spin" />
        </main>
        <Footer />
      </div>
    );
  }

  return (
    <div className="flex flex-col min-h-screen">
      <Navbar />
      <main className="flex-1 max-w-7xl mx-auto w-full px-4 sm:px-6 lg:px-8 py-8">
        <div className="max-w-2xl mx-auto page-enter">
          <Link href="/" className="inline-flex items-center gap-1.5 text-sm text-slate-500 hover:text-indigo-600 mb-6 transition-colors font-semibold">
            <ChevronLeft size={16}/> Back to Dashboard
          </Link>

          <div className="flex items-center gap-3 mb-6">
            <div className="w-12 h-12 rounded-2xl grad-primary flex items-center justify-center shadow-lg">
              <Calculator size={22} className="text-white"/>
            </div>
            <div>
              <h1 className="text-2xl font-extrabold text-slate-800">Tax Calculation</h1>
              <p className="text-sm text-slate-400">5% flat rate on all linked bank balances</p>
            </div>
          </div>

          <div className="flex items-start gap-3 bg-amber-50 border border-amber-200 rounded-xl p-3.5 mb-5">
            <AlertTriangle size={15} className="text-amber-500 shrink-0 mt-0.5"/>
            <p className="text-xs text-amber-700 leading-relaxed">
              Tax is calculated at a flat <strong>5%</strong> on each bank's current balance. This is a simplified demo model only.
            </p>
          </div>

          {/* Bank breakdown */}
          <div className="bg-white rounded-2xl shadow-sm border border-slate-100 overflow-hidden mb-5">
            <div className="px-5 py-4 border-b border-slate-100 bg-slate-50 flex items-center gap-2">
              <CreditCard size={14} className="text-slate-400"/>
              <h2 className="text-sm font-bold text-slate-700">Bank-wise Tax Breakdown</h2>
            </div>
            <div className="divide-y divide-slate-50">
              {banks.map((bank,i) => {
                const tax     = bank.balance * TAX_RATE;
                const pct     = totalTax>0 ? (tax/totalTax)*100 : 0;
                return (
                  <div key={bank.id} className="px-5 py-4">
                    <div className="flex items-start justify-between mb-2">
                      <div>
                        <div className="flex items-center gap-2">
                          <span className="w-5 h-5 rounded-full grad-primary text-white text-[10px] font-bold flex items-center justify-center shrink-0">{i+1}</span>
                          <p className="text-sm font-bold text-slate-800">{bank.bankName}</p>
                        </div>
                        <p className="text-xs text-slate-400 mt-0.5 ml-7">Balance: <span className="number-display font-semibold text-slate-600">{formatCurrency(bank.balance)}</span></p>
                      </div>
                      <div className="text-right">
                        <p className="number-display text-sm font-extrabold text-rose-500">{formatCurrency(tax)}</p>
                        <p className="text-xs text-slate-400">@ 5%</p>
                      </div>
                    </div>
                    <div className="ml-7 h-1.5 bg-slate-100 rounded-full overflow-hidden">
                      <div className="h-full grad-primary rounded-full transition-all duration-700" style={{width:`${pct}%`}}/>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>

          {/* Summary card */}
          <div className="grad-dark rounded-2xl p-6 mb-5 text-white relative overflow-hidden">
            <div className="absolute -top-12 -right-12 w-44 h-44 rounded-full bg-white opacity-[0.04]"/>
            <div className="absolute -bottom-10 -left-10 w-36 h-36 rounded-full bg-white opacity-[0.04]"/>
            <div className="relative z-10">
              <div className="flex items-center gap-2 mb-4">
                <TrendingUp size={15} className="text-indigo-300"/>
                <span className="text-[10px] uppercase tracking-widest text-white/40 font-semibold">Tax Summary</span>
              </div>
              <div className="grid grid-cols-3 gap-4">
                <div>
                  <p className="text-[10px] uppercase tracking-widest text-white/40 mb-1">Total Balance</p>
                  <p className="number-display text-base font-extrabold text-white">{formatCurrency(totalBalance)}</p>
                </div>
                <div>
                  <p className="text-[10px] uppercase tracking-widest text-white/40 mb-1">Tax Rate</p>
                  <p className="number-display text-xl font-extrabold text-indigo-300">5.00%</p>
                </div>
                <div>
                  <p className="text-[10px] uppercase tracking-widest text-white/40 mb-1">Total Tax Due</p>
                  <p className="number-display text-xl font-extrabold text-emerald-400">{formatCurrency(totalTax)}</p>
                </div>
              </div>
              <div className="mt-4 pt-4 border-t border-white/10 flex items-center gap-2 text-xs text-white/40">
                <CheckCircle2 size={12} className="text-emerald-400"/>
                Based on {banks.length} linked bank account{banks.length!==1?"s":""}
              </div>
            </div>
          </div>

          {/* Buttons */}
          <div className="grid grid-cols-2 gap-3">
            <button onClick={handlePayTax}
              className="grad-primary text-white font-bold py-3.5 rounded-xl hover:opacity-90 active:scale-[0.98]
                transition-all shadow-lg flex items-center justify-center gap-2 text-sm">
              <CreditCard size={16}/> Pay Tax
            </button>
            <button onClick={handleDownload}
              className="bg-white border-2 border-slate-200 text-slate-700 font-bold py-3.5 rounded-xl
                hover:border-indigo-400 hover:text-indigo-600 active:scale-[0.98] transition-all shadow-sm
                flex items-center justify-center gap-2 text-sm">
              <Download size={16}/> Download Tax Paper
            </button>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
}
